name: mychoice
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5
  animate_do: ^4.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  standard_searchbar: ^2.1.1
  carousel_slider: ^5.1.1
  flutter_bounceable: ^1.2.0
  double_back_to_exit: ^1.2.1
  video_player: ^2.9.5
  fluttertoast: ^8.2.12
  another_flushbar: ^1.12.30
  bottom_sheet: ^4.0.4
  google_maps_flutter: ^2.10.1
  curved_navigation_bar: ^1.0.6
  skeletonizer: ^1.4.3
  font_awesome_flutter: ^10.9.0
  flashy_tab_bar2: ^0.0.10
  date_time: ^0.12.0
  table_calendar: ^3.2.0
  transformer_page_view_tv: ^0.1.7-nullsafety
  flutter_custom_carousel: ^0.1.0+1
  flutter_advanced_segment: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.1.2
  widget_loading: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Urban Experts.png"
  min_sdk_android: 21

  
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/vedios/
  #   - images/a_dot_ham.jpeg

 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
